crowdFunding/crowdFunding/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import projectSearchView, products_index,about_page

urlpatterns = [
    path('', products_index, name='home_page'),
    path('about', about_page, name='about_page'),
    path('search', projectSearchView.as_view(), name='projects.search'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('project/', include('project.urls')),
    path('commentary/', include('commentary.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdFunding/project/urls.py
from project.views import ( create_project_model_form,
    list_project, cancel_project,project_show, donate_project, edit_project,
                            add_images,clear_images)
from commentary.views import add_comment
from django.urls import path

urlpatterns = [
    # path("hello", hello, name= "hello"),
    path('<int:id>/comment', add_comment, name='project.comment'),
    path('createproject', create_project_model_form, name='project.createmodel'),
    path('<int:id>', project_show, name='project.show'),
    path('cancelproject/<int:id>', cancel_project, name='project.cancel'),
    path('', list_project, name='project.list'),
    path('donate/<int:id>', donate_project, name='project.donate'),
    path('<int:id>/edit', edit_project, name='project.edit'),
    path('<int:id>/addimage', add_images, name='project.addimage'),
    path('<int:id>/clearimage', clear_images, name='project.clearimage'),
    
    

]

crowdFunding/users/urls.py
from django.urls import path,include
from users.views import (user_details,login_form,register, user_delete,activate,featured_projects,
                         add_to_featured,user_edit,admin_dashboard,category_index,delete_category,
                         edit_category,add_category,tag_index,add_tag,edit_tag,delete_tag,
                         user_index,delete_user_by_admin,add_user_by_admin,
                         edit_user_by_admin,user_donations,user_projects,
                         categories_project,user_logout,delete_project_by_admin,
                         reported_comment_index,delete_reported_comment)

urlpatterns = [
    path('register/', register, name="user.register"),
    path('edit/<int:id>', user_edit, name="user.edit"),
    path('login/', login_form, name="user.login"),
    path('details/<int:id>',user_details , name="user.details"),
    path('delete/<int:id>',user_delete , name="user.delete"),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('admin/', admin_dashboard , name="admin.dashboard"),
    path('admin/category/', category_index , name="category.index"),
    path('admin/category/<int:id>/delete', delete_category, name='category.delete'),
    path('admin/category/<int:id>/edit', edit_category, name='category.edit'),
    path('admin/category/add', add_category, name='category.add'),
    path('admin/tag/', tag_index, name='tag.index'),
    path('admin/tag/add', add_tag, name='tag.add'),
    path('admin/tag/<int:id>/edit', edit_tag, name='tag.edit'),
    path('admin/tag/<int:id>/delete', delete_tag, name='tag.delete'),
    path('admin/featured/', featured_projects, name="featured"),
    path('admin/user/', user_index, name='user.index'),
    path('admin/user/<int:id>/delete', delete_user_by_admin, name='user.delete.by.admin'),
    path('admin/user/add/', add_user_by_admin, name='add.user.by.admin'),
    path('admin/user/<int:id>/edit', edit_user_by_admin, name='edit.user.by.admin'),
    # path('featured/', featured_projects , name="featured"),
    path('add_to_featured/<int:id>', add_to_featured, name="add.to.featured"),
    path('donations/<int:id>', user_donations , name="user.donations"),
    path('projects/<int:id>', user_projects , name="user.projects"),
    path('categories', categories_project , name="categories.projects"),
    path('logout/', user_logout, name='logout'),
    path('admin/featured/<int:id>/delete', delete_project_by_admin, name='delete.project.by.admin'),
    path('admin/reported-comments/', reported_comment_index, name="reported.comment.index"),
    path('admin/reported-comments/<int:id>/delete', delete_reported_comment, name="delete.reported.comment"),

]

crowdFunding/commentary/models.py
from django.db import models
from project.models import Project
from users.models import User
from django.shortcuts import reverse


class Comment(models.Model):
    text=models.TextField(null=True)
    rate= models.IntegerField(default=0)
    project = models.ForeignKey(Project,on_delete=models.CASCADE,related_name='comments')
    user =models.ForeignKey(User,on_delete=models.CASCADE,related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.id}'






class Report(models.Model):
    reason = models.CharField(max_length=500)
    status = models.CharField(max_length=25)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='reports')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='reports', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.reason


class Reply(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='replies')
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE, related_name='replies')
    product = models.ForeignKey(Project,on_delete=models.CASCADE, related_name='replies', null=True)
    content = models.CharField(max_length=500, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

crowdFunding/project/forms.py
from django import forms
from project.models import Project,Tag,Category,Donation,Picture
from datetime import datetime
from django.utils import timezone

class ProjectModelForm(forms.ModelForm):    
    class Meta:
        model = Project
        fields = ('title', 'details', 'total_target', 'start_date', 'end_date','category', 'tag')
        
    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')

        if start_date and end_date:
            if end_date <= start_date:
                raise forms.ValidationError('End date must be greater than start date')

        return cleaned_data
    
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 3:
            raise forms.ValidationError('Title length must be greater then 3 characters')
        return title
    
    def clean_total_target(self):
        total_target = self.cleaned_data['total_target']
        if total_target <= 5000:
            raise forms.ValidationError("Total target must be grater than 5000.")
        return total_target
    
    def clean_start_date(self):
        start_date = self.cleaned_data['start_date']
        if start_date < datetime.now().date():
            raise forms.ValidationError('Start date must be greater than today')
        return start_date


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name.isalpha():
            raise forms.ValidationError('Category name must be alphabetic')
        if name is None or len(name) < 3:
            raise forms.ValidationError('Category name should be at least 3 characters')
        return name


class TagModelForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name.isalpha():
            raise forms.ValidationError('Tag name must be alphabetic')
        if name is None or len(name) < 3:
            raise forms.ValidationError('Tag name should be at least 3 characters')
        return name


class DonationModelForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ('donation',)
        
    def clean_donation(self):
        donation = self.cleaned_data['donation']
        if donation <= 0:
            raise forms.ValidationError("Donation amount must be positive.")
        return donation
        
    
    
    
class PictureModelForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['image']
        
    def clean_image(self):
        image = self.cleaned_data.get('image')
        if not image:
            raise forms.ValidationError("You must upload an image.")
        return image

crowdFunding/project/views.py
from django.shortcuts import render, redirect,get_object_or_404,reverse
from project.models import Project, Category,Picture
from project.forms import ProjectModelForm,CategoryModelForm,TagModelForm
from commentary.forms import CommentForm,ReportForm, ReplyForm
from project.models import Project , Donation
from project.forms import ProjectModelForm,CategoryModelForm,TagModelForm,DonationModelForm,PictureModelForm
from commentary.forms import CommentForm,ReportForm
from commentary.models import Comment
from django.db.models import F
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required,user_passes_test
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.http import JsonResponse
from django.core.files import File
from django.conf import settings
import os
from pathlib import Path
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required
from django.http import Http404
from users.views import check_superuser,check_user


# def hello(request):
#     print(request)
#     return render(request, 'test.html', {'name': 'Hello'})

@login_required
@user_passes_test(check_user)
def create_project_model_form(request):
    if request.method == 'POST':
        form = ProjectModelForm(request.POST, request.FILES)        
        if form.is_valid():
            project = form.save(commit=False)
            project.project_owner = request.user
            project.save()
            form.save_m2m()
            return redirect(project.show_url)
    else:
        form = ProjectModelForm()
        
    return render(request, 'project/forms/createmodel.html', {'form': form})


@login_required
def project_show(request,id):
    # project = get_object_or_404(Project, pk=id)
    try:
        project = Project.objects.get(pk=id)
    except Project.DoesNotExist:

        return render(request, 'project/crud/badrequest.html')
    images = project.images.all()
    comments = project.comments.all()
    reports = project.reports.all()
    reviews_reply = project.comments.prefetch_related('replies')
    form = CommentForm()
    form2 = ReportForm()
    reply_form = ReplyForm()
    owner_name = project.project_owner.first_name
    if project.total_target != 0:
        progress_percentage = (project.current_donation / project.total_target) * 100
    else:
        progress_percentage = 0
    return render(request, "project/crud/show.html",
                context={"project": project,'images': images, 'comments': comments,'owner_name': owner_name, 'reports': reports,
                        'form': form, 'form2': form2, "reply_form":reply_form, "reviews_reply":reviews_reply
                        , 'progress_percentage': progress_percentage})


@login_required
def cancel_project(request, id):
    try:
        project = Project.objects.get(pk=id)
    except Project.DoesNotExist:

        return render(request, 'project/crud/badrequest.html')
    
    # Check if the current user is the owner of the project
    if request.user == project.project_owner:
        total_target = project.total_target
        donation = project.current_donation
        if donation < total_target * 0.25:
            project.delete()
            return redirect(project.list_url)
        else:
            error_message = 'The donation is greater than 25%'
            # return render(request, 'project/crud/show.html', {'error_message': error_message})
            redirect_url = f"{project.show_url}?error_message={error_message}"
            return redirect(redirect_url)
            
    else:
        # If the current user is not the owner, handle unauthorized access
        # For example, you can return a 403 Forbidden response or redirect to a different page
        return HttpResponseForbidden("You are not authorized to perform this action.") 


def list_project(request):
    projects = Project.objects.all()
    return render(request, 'project/crud/list.html', {'projects': projects})


@login_required
@user_passes_test(check_user)
def donate_project(request, id):
    try:
        project = Project.objects.get(pk=id)
    except Project.DoesNotExist:

        return render(request, 'project/crud/badrequest.html')
    
    if project.is_run_project() == False:
        return HttpResponseForbidden("the project is not run")

    if request.method == 'POST':
        form = DonationModelForm(request.POST)
        if form.is_valid():
            donation = form.save(commit=False)
            donation.project = project
            donation.user = request.user
            donation.save()
            
            # Increase the current donation for the project
            project.current_donation += donation.donation
            project.save()
            # Redirect to project details page or any other desired page
            return redirect(project.show_url, id=id, project=project)  

    else:
        form = DonationModelForm()

    return render(request, 'project/crud/donate.html', {'form': form, 'project': project})



@login_required
@user_passes_test(check_user)
def edit_project(request, id):
    try:
        project = Project.objects.get(pk=id)
    except Project.DoesNotExist:
        return render(request, 'project/crud/badrequest.html')
    if request.user == project.project_owner:
        form = ProjectModelForm(instance=project)
        if request.method == "POST":
            form = ProjectModelForm(request.POST, request.FILES, instance=project)
            if form.is_valid():
                project = form.save()
                return redirect(project.show_url)

        return render(request, 'project/crud/edit.html', context={"form": form})
    else:
        return render(request, 'project/crud/badrequest.html')


@login_required
@user_passes_test(check_user)
def add_images(request, id):
    try:
        project = Project.objects.get(pk=id)
    except Project.DoesNotExist:

        return render(request, 'project/crud/badrequest.html')
    if request.user == project.project_owner:
        if request.method == 'POST':
            form = PictureModelForm(request.POST, request.FILES)
            if form.is_valid():
                # Get the list of image files from the request
                image_files = request.FILES.getlist('image')

                # Iterate over each image file
                for image_file in image_files:
                    # Create a new Picture instance
                    picture = Picture(image=image_file, project=project)
                    picture.save()

                # Redirect or render a success page
                return redirect(project.show_url)
        else:
            form = PictureModelForm()
        return render(request, 'project/forms/add_image.html', {'form': form})
    else:
        return render(request, 'project/crud/badrequest.html')

@login_required
@user_passes_test(check_user)
def clear_images(request, id):
    try:
        project = Project.objects.get(pk=id)
    except Project.DoesNotExist:

        return render(request, 'project/crud/badrequest.html')
    if request.user == project.project_owner:
        for picture in project.images.all():
            picture.image.delete()  # This will delete the image file from the storage
            picture.delete()  # This will delete the Picture instance from the database
        return redirect(project.show_url)
    else:
        return render(request, 'project/crud/badrequest.html')

crowdFunding/project/templates/project/crud/badrequest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthorized Access</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-danger text-white">
                        Unauthorized Access
                    </div>
                    <div class="card-body">
                        <p class="card-text">Error 404</p>
                        <p class="card-text">Please <a href="{% url 'project.list' %}" class="btn btn-primary">go back to the homepage</a> or contact the administrator for assistance.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

crowdFunding/project/templates/project/crud/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
<h1 class="text-center text-success fw-bold fst-italic fs-1 my-3 text-capitalize">Edit Project</h1>
<div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="btn btn-success my-2">
</form>
</div>
<script src = "{% static 'project/js/script.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>
{% endblock %}

crowdFunding/project/templates/project/crud/show.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/showPage.css' %}">
{% endblock %}


<title>Project Details</title>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<!-- Bootstrap Bundle with Popper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js" integrity="sha512-AkTRX81q0DXii1alvMYq8F8TmDLn9/8GzuFtH/FuHeEMwSapVSZU8TpC0uY6PGhBmToXGZZqHQ3lvg5GkDF7ow==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


{% block content %}

<div class="container">
{% if images %}
<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    {% for image in images %}
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></button>
    {% endfor %}
  </div> 
  <div class="carousel-inner">
    {% for image in images %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}" style="width: 100%; height: 75vh;">
        {% if image.image %}
         <img src="{{ image.image.url }}" class="d-block w-100 h-100" alt="Image {{ forloop.counter }}">
          {% comment %} <img src="{{ image.image.url }}" class="d-block" style="width: 100%; height: 100%;" alt="Image {{ forloop.counter }}"> {% endcomment %}

        {% else %}
          <!-- Provide the URL of the alternative image -->
          <img src="/media/project/images/default.jpg" class="d-block w-100" alt="Image {{ forloop.counter }}">
        {% endif %}
      </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% else %}
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <img src="/media/project/images/default.jpg" class="w-50 h-75" alt="Default Image">
</div>

{% endif %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


    <div class="card">
      
        <div class="card-body">
            <div class="card bg-dark text-white" style="background: linear-gradient(135deg, #333333 , #007bff);">
            <h4><span class="label">Project Owner:</span> {{ owner_name }}</h4>    
        <h5 class="card-title my-2">Title is {{ project.title }}</h5>
    <div class="card-body">
        <div class="project-info">
            <p><span class="label">Details:</span> {{ project.details }}</p>
             <div class="progress mb-3">
        <div class="progress-bar bg-success" role="progressbar" 
        style="width:  {{ progress_percentage }}%" aria-valuenow="{{ project.current_donation }}" 
        aria-valuemin="0" aria-valuemax="{{ project.total_target }}"></div>
       </div>
    
            <p><span class="label">Total Target:</span> {{ project.total_target }}$</p>
            <p><span class="label">Current Donation:</span> {{ project.current_donation }}$</p>

            <p><span class="label">Start Date:</span> {{ project.start_date }}</p>
            <p><span class="label">End Date:</span> {{ project.end_date }}</p>
            <p>Tags: </p>
            {% for tag in project.tag.all %}
            <p><span class="label"></span> {{  tag.name  }}</p>
            {% endfor %}
            </div>
        </div>
    </div>

            

                <!-- Include Font Awesome CSS -->
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
                      integrity="sha512-QzlcmlSdIbDtiRJInF4VaNmDTuK25I7RQ1SfJM/f1iDn2JN84iXT2AKI5ffj5wdsW0RnW7fuyBdVFlk2l4OfCw=="
                      crossorigin="anonymous" referrerpolicy="no-referrer"/>

                <!-- Display stars -->
                <div class="rate">
                    {% for star in project.star_ratings %}
                    {% if star == 0.5 %}
                    <i class="fas fa-star-half-alt" style="color: orange;"></i>
                    {% elif star == 0 %}
                    <i class="far fa-star" style="color: black;"></i>
                    {% else %}
                    <i class="fas fa-star" style="color: orange;"></i>
                    {% endif %}
                    {% endfor %}
                </div>
                {% if project.id %}
                <a href="{% url 'projects.report_project' project.id %}" class="btn btn-primary report-button">
                    <i class="fas fa-flag"> Report</i>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container my-2 d-flex justify-content-center align-items-center">
    {% if project.is_run_project %}
    <a href="{{ project.donate_url }}" class="btn btn-success mx-1">Donate Now</a>
    {% endif %}
    {% if request.user == project.project_owner %}
    <a href="{{ project.delete_url }}" id="delete-project-btn" class="btn btn-danger"
    data-bs-toggle="modal" data-bs-target="#exampleModal{{project.id}}">Delete Project</a>
    <a href="{{ project.edit_url }}" class="btn btn-primary mx-1">Edit Project</a>
    <a href="{{ project.add_image_url }}" class="btn btn-success mx-1">Add Images</a>
    <a href="{{ project.clear_url }}" class="btn btn-danger">Clear All Images</a>


    {% if request.GET.error_message %}
    <div class="alert alert-danger">
        {{ request.GET.error_message }}
    </div>
    {% endif %}
{% endif %}
</div>


<div class="modal fade" id="exampleModal{{project.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure to delete?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a href="{{project.delete_url}}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>


    {% if messages %}
    <div class="messages alert alert-success text-center list-unstyled w-25 m-auto">
        {% for message in messages %}
            <li class="nav-item ">{{ message }}</li>
        {% endfor %}
    </div>
    {% endif %}

<!-- jQuery (Optional) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap Bundle with Popper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js" integrity="sha512-AkTRX81q0DXii1alvMYq8F8TmDLn9/8GzuFtH/FuHeEMwSapVSZU8TpC0uY6PGhBmToXGZZqHQ3lvg5GkDF7ow==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>



<div class="comments-box">
    <div class="comments-container">
        <!--        <h3>Comments</h3>-->
        {% if comments %}
        <div class="comment-list">
            {% for comment in comments %}
            <div class="comment">
                {% comment %} <div class="comment-user"> {{ comment.user }}</div> {% endcomment %}

                <div class="comment-user">User: {{ comment.user }}</div>
                <div class="comment-text">{{ comment.text }}</div>

                {% if not comment.reported %}
                <form method="post" action="{% url 'projects.report_comment' id=project.id comment_id=comment.id %}">
                    {% csrf_token %}
                    {% comment %}
                    <button type="submit" class="report-button btn btn-primary">Report</button>
                    {% endcomment %}
                    <button type="submit" class="report-button btn btn-primary">
                        <i class="fas fa-flag"></i>
                    </button>


                </form>
                {% else %}
                <span class="reported">Reported</span>
                {% endif %}

                {% for reply in comment.replies.all %}
                <div class="reply">
                    <div class="reply-user">User: {{ reply.user }}</div>
                    <div class="reply-content">{{ reply.content }}</div>
                    <div class="reply-time">{{ reply.created_at }}</div>
                </div>
                {% endfor %}

                <!-- Reply form -->
                <form method="post" action="{% url 'projects.reply' project.id comment.id %}">
                    {% csrf_token %}
                    {% comment %} {% if messages %}
            <ul class="messages alert alert-success text-center list-unstyled">
                {% for message in messages %}
                    <li class="nav-item ">{{ message }}</li>
                {% endfor %}
            </ul>
                  {% endif %} {% endcomment %}
                    {{ reply_form.as_p }}
                    <button type="submit">Reply</button>
                </form>


            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>No comments yet.</p>
        {% endif %}

        <!-- Add Comment Form -->
        <button id="add-comment-btn">Add Comment</button>
        <!--        <p>Project ID: {{ project.id }}</p>-->
        <form class="add-comment-form" method="post" action="{% url 'project.comment' project.id %}"
        style="display: none;" >
            
            {% csrf_token %}


   {{ form.errors }}

            {{ form.as_p }}

            <div class="rating" >
                <input type="radio" id="star5" name="star_rating" value="5">
                <label for="star5">&#9733;</label>

                <input type="radio" id="star4" name="star_rating" value="4">
                <label for="star4">&#9733;</label>

                <input type="radio" id="star3" name="star_rating" value="3">
                <label for="star3">&#9733;</label>

                <input type="radio" id="star2" name="star_rating" value="2">
                <label for="star2">&#9733;</label>

                <input type="radio" id="star1" name="star_rating" value="1">
                <label for="star1">&#9733;</label>
            </div>
            <input type="hidden" id="id_rate" name="star_rating">


            <!--            <textarea name="text" id="comment_text" placeholder="Write your comment here..." required></textarea>-->
            <button type="submit" id="submit-comment-btn">Submit</button>
        </form>
    </div>
</div>

{% comment %} project with similar tags {% endcomment %}
<div class="container">
            <h4 class="text-center text-success fw-bold fst-italic fs-1 my-3 text-capitalize">See Also :: Projects with Same Tags</h4>

    <div class="row justify-content-center">
        {% for tag in project.tag.all %}
            <div class="col-md-4">
                <div class="card text-white mt-3" style="background: linear-gradient(135deg, #333333 , #007bff);">
                    <div class="card-body">
                        <h5 class="card-title">Tag Name: {{ tag.name }}</h5>
                        <ul class="list-unstyled">
                            {% for related_project in tag.projects.all %}
                                {% if forloop.counter <= 4 and related_project != project %}
                                    <li>
                            <div class="rounded-2 my-1" style="background-color: black; padding: 5px;">
                                <a href="{{ related_project.show_url }}" class="text-white text-decoration-none">Project: {{ related_project.title }}</a>
                            </div>
                            </li>

                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.bundle.min.js" integrity="sha512-Ry4FzxO9+ri4OkYyLgSaxRuWcsM2b9hjNKeJAd6D8/5xtHqjAW90DXv+XHtgr7pZCHZjy9t5A5pt0YKgKx2/7A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


<script src="{% static 'project/js/index.js'%}"></script> 
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const rateInput = document.getElementById('id_rate');
        rateInput.style.display = 'none'; // Hide the input field
    });
</script>


{% endblock %}