crowdFunding/crowdFunding/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import projectSearchView, products_index,about_page

urlpatterns = [
    path('', products_index, name='home_page'),
    path('about', about_page, name='about_page'),
    path('search', projectSearchView.as_view(), name='projects.search'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('project/', include('project.urls')),
    path('commentary/', include('commentary.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdFunding/users/urls.py
from django.urls import path,include
from users.views import (user_details,login_form,register, user_delete,activate,featured_projects,
                         add_to_featured,user_edit,admin_dashboard,category_index,delete_category,
                         edit_category,add_category,tag_index,add_tag,edit_tag,delete_tag,
                         user_index,delete_user_by_admin,add_user_by_admin,
                         edit_user_by_admin,user_donations,user_projects,
                         categories_project,user_logout,delete_project_by_admin,
                         reported_comment_index,delete_reported_comment)

urlpatterns = [
    path('register/', register, name="user.register"),
    path('edit/<int:id>', user_edit, name="user.edit"),
    path('login/', login_form, name="user.login"),
    path('details/<int:id>',user_details , name="user.details"),
    path('delete/<int:id>',user_delete , name="user.delete"),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('admin/', admin_dashboard , name="admin.dashboard"),
    path('admin/category/', category_index , name="category.index"),
    path('admin/category/<int:id>/delete', delete_category, name='category.delete'),
    path('admin/category/<int:id>/edit', edit_category, name='category.edit'),
    path('admin/category/add', add_category, name='category.add'),
    path('admin/tag/', tag_index, name='tag.index'),
    path('admin/tag/add', add_tag, name='tag.add'),
    path('admin/tag/<int:id>/edit', edit_tag, name='tag.edit'),
    path('admin/tag/<int:id>/delete', delete_tag, name='tag.delete'),
    path('admin/featured/', featured_projects, name="featured"),
    path('admin/user/', user_index, name='user.index'),
    path('admin/user/<int:id>/delete', delete_user_by_admin, name='user.delete.by.admin'),
    path('admin/user/add/', add_user_by_admin, name='add.user.by.admin'),
    path('admin/user/<int:id>/edit', edit_user_by_admin, name='edit.user.by.admin'),
    # path('featured/', featured_projects , name="featured"),
    path('add_to_featured/<int:id>', add_to_featured, name="add.to.featured"),
    path('donations/<int:id>', user_donations , name="user.donations"),
    path('projects/<int:id>', user_projects , name="user.projects"),
    path('categories', categories_project , name="categories.projects"),
    path('logout/', user_logout, name='logout'),
    path('admin/featured/<int:id>/delete', delete_project_by_admin, name='delete.project.by.admin'),
    path('admin/reported-comments/', reported_comment_index, name="reported.comment.index"),
    path('admin/reported-comments/<int:id>/delete', delete_reported_comment, name="delete.reported.comment"),

]

crowdFunding/project/models.py
from django.db import models
from django.shortcuts import get_object_or_404 , reverse
from django.utils import timezone
from users.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def get_category_by_id(cls, id):
        return get_object_or_404(cls,pk=id)

    @property
    def delete_url(self):
        url=reverse ("category.delete",args=[self.id])
        return url

    @property
    def show_url(self):
        url=reverse("category.show",args=[self.id])
        return url

    @property
    def edit_url(self):
        return reverse("category.edit",args=[self.id])


class Tag(models.Model):
    name = models.CharField(max_length=100, null=True,unique=True)

    def __str__(self):
        return self.name

    @classmethod
    def get_tag_by_id(cls, id):
        return get_object_or_404(cls, pk=id)

    @property
    def delete_url(self):
        url = reverse("tag.delete", args=[self.id])
        return url

    # @property
    # def show_url(self):
    #     url = reverse("tag.show", args=[self.id])
    #     return url

    @property
    def edit_url(self):
        return reverse("tag.edit", args=[self.id])



class Project(models.Model):
    title = models.CharField(max_length=200, unique=True)
    details = models.TextField(default="No details")
    total_target = models.FloatField()
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    current_donation = models.FloatField(default=0, null=True, blank=True)
    project_owner=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    featured_at = models.DateTimeField(default=None, null=True, blank=True)
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, blank=True, related_name="projects")
    is_run = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    @property
    def show_url(self):
        url = reverse('project.show', args=[self.id])
        return url

    @property
    def edit_url(self):
        url = reverse('project.edit', args=[self.id])
        return url
    @property
    def list_url(self):
        url = reverse('project.list')
        return url
    

    @classmethod

    def get_project_by_id(cls,id):
        return get_object_or_404(cls, pk=id)

    
    @property
    def delete_url(self):
        url = reverse('project.cancel', args=[self.id])
        return url

    
    @property
    def clear_url(self):
        url = reverse('project.clearimage', args=[self.id])
        return url
    
    @property
    def rate(self):
        comments = self.comments.all()
        if comments.exists():
            return round(sum(comment.rate for comment in comments) / len(comments), 1)
        return 0

    @property
    def star_ratings(self):
        rate = self.rate
        return [1 if i < rate else 0.5 if abs(i - rate) <= 0.5 else 0 for i in range(1, 6)]
    @property
    def donate_url(self):
        url = reverse('project.donate', args=[self.id])
        return url

    def featured_project(self):
        if not self.is_featured:
            self.is_featured=True
            self.featured_at=timezone.now()
            self.save()

    def not_featured_project(self):
        if self.is_featured:
            self.is_featured=False
            self.featured_at=None
            self.save()

    def image_urls(self):
        return [image.image.url for image in self.images.all()]
    
    def is_run_project(self):
        
        if self.end_date < timezone.now().date():
            self.is_run = False
            self.save(update_fields=['is_run'])
        return self.is_run
    
    @property
    def add_image_url(self):
        url = reverse('project.addimage', args=[self.id])
        return url

class Picture(models.Model):
    image = models.ImageField(upload_to='project/images/', null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE , related_name='images')

    def __str__(self):
        return f"/media/{self.image}"



class Donation(models.Model):
    donation=models.FloatField()
    project=models.ForeignKey(Project, on_delete=models.CASCADE, related_name='donations')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    

    def __str__(self):
        return self.donation
    
    

crowdFunding/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator,FileExtensionValidator
from datetime import date
from django.core.exceptions import ValidationError
from django.shortcuts import reverse, get_object_or_404
from django.forms import TimeField


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, first_name, last_name, phone, birth_date, **extra_fields):
        if not email:
            raise ValueError("Email must be provided")
        if not password:
            raise ValueError('Password is not provided')
        user = self.model(
            email=self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            phone = phone,
            birth_date = birth_date,
            # photo = photo
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, first_name, last_name, phone, birth_date, **extra_fields):
        extra_fields.setdefault('is_superuser',False)
        return self._create_user(email, password, first_name, last_name, phone, birth_date, **extra_fields)

    def create_superuser(self, email, password, first_name, last_name, phone ,birth_date, **extra_fields):
        extra_fields.setdefault('is_superuser',True)
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_active',True)
        return self._create_user(email, password, first_name, last_name, phone, birth_date, **extra_fields)


AUTH_PROVIDERS = {'facebook': 'facebook', 'email': 'email'}


class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(db_index=True, unique=True, max_length=254,blank=True)
    first_name = models.CharField(max_length=240,blank=True)
    last_name = models.CharField(max_length=255,blank=True)
    phone = models.CharField(max_length=50, validators=[RegexValidator(r'^01[0-2,5]{1}[0-9]{8}$')],blank=True)
    address = models.CharField( max_length=250)
    photo = models.ImageField(upload_to='users/images',blank=True, validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    birth_date = models.DateField(null=True, blank=True)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    country = models.CharField(null=True,blank=True, max_length=225)
    facebook = models.URLField(null=True, blank=True)
    auth_provider = models.CharField(
        max_length=255, blank=False,
        null=False, default=AUTH_PROVIDERS.get('email'))

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["first_name", "last_name", "phone","birth_date","photo"]

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    @property
    def photo_url(self):
        return f"/media/{self.photo}"

crowdFunding/users/templates/users/categories_projects.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link href="{% static 'users/css/styles.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}

    <div class="container">
        <h1 class="text-center text-success fw-bold fst-italic fs-1 my-3 text-capitalize">Categories and Projects</h1>
        <div class="accordion" id="categoryAccordion">
            {% for category in categories %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ category.id }}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ category.id }}" aria-expanded="false" aria-controls="collapse{{ category.id }}">
                        {{ category.name }}
                    </button>
                </h2>
                <div id="collapse{{ category.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ category.id }}" data-bs-parent="#categoryAccordion">
                    <div class="accordion-body">
                        <ul>
                            {% for project in category.project_set.all %}
                            <li><a href="{% url 'project.show' project.id %}">{{ project.title }}</a></li>
                            {% empty %}
                            <li class="text-danger">No projects in this category.</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-center text-danger fw-bold fs-3 text-capitalize mb-3">No categories found.</p>
            {% endfor %}
        </div>
    </div>

{% endblock %}

crowdFunding/users/templates/users/index.html
{% extends 'landing_page.html' %} 

{% block message %} 
{% include 'users/includes/messaging.html'%}
{% endblock %}

crowdFunding/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2 class="text-center">Login</h2>

<form method = "post" enctype="multipart/form-data" class="mx-auto w-50 row">
    {% csrf_token %}

    {{form}}
    <input type="submit" class="btn btn-primary mx-auto justify-content-center w-25 mt-5">

</form>

<style>
<!--    input[type="password"],input[type="text"]{-->
<!--        width: 50%;-->
<!--        margin:auto;-->
<!--    }-->
    .form-group{
<!--        width: 50%;-->
        margin: auto;
<!--        margin-bottom:20px;-->
    }
<!--    label[for="username"],label[for="password"]{-->
<!--        text-align:center;-->

<!--        }-->
    input[type="submit"]{
<!--        margin-top: 10px;-->
<!--        width: 8rem;-->


    }
</style>

<script>
<!--    var formGroup=document.querySelectorAll(".form-group");-->
<!--    formGroup.classList.add("justify-content-center");-->
</script>
<script src ="{% static 'users/js/formStyles.js' %}"></script>

{% endblock %}

crowdFunding/users/templates/users/register.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<style>
        input{
            width:fit-content: !important;
        }
        body{
            background-color: lightgray;
        }
    </style>
<h2 class="text-center mt-5">Register</h2>

<form method = "post" enctype="multipart/form-data" class="row w-50 mx-auto mt-5">
{% csrf_token %}
{{form}}
<input type="submit" value="Submit" class="btn btn-primary mx-auto w-25 my-3">
</form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<!--<style>-->
<!--    input[type="file"]{-->
<!--    margin-top:20px-->
<!--    }-->
<!--</style>-->
<script src="{% static 'users/js/formStyles.js' %}"></script>

{% endblock %}

crowdFunding/users/templates/users/unauthorized.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthorized Access</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-danger text-white">
                        Unauthorized Access
                    </div>
                    <div class="card-body">
                        <p class="card-text">Sorry, you are not authorized to view this page.</p>
                        <p class="card-text">Please <a href="{% url 'home_page' %}" class="btn btn-primary">go back to the homepage</a> or contact the administrator for assistance.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

crowdFunding/users/templates/users/user_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-2">
  <h1 class="text-center text-success fw-bold fst-italic fs-1">User Details</h1>
  <div class="row">
    <div class="col-md-4 mb-3">
                    {% if user.photo %}
                        <img src="{{ user.photo.url }}" alt="user photo" class="img-fluid rounded"">
                    {% else %}
                        <img src="{% static 'users/media/default-user.jpg' %}" alt="default user photo" class="img-fluid rounded">
                    {% endif %}
      {% if user.is_superuser %}
      <p class="text-center text-danger fs-3">
        <strong>Admin</strong>
      </p>
      {% endif %}
    </div>

    <div class="col-md-8">
      <ul class="list-group">
        <li class="list-group-item">
          <strong>First Name:</strong> {{ user.first_name }}
        </li>
        <li class="list-group-item">
          <strong>Last Name:</strong> {{ user.last_name }}
        </li>
        <li class="list-group-item">
          <strong>Email:</strong> {{ user.email }}
        </li>
        <li class="list-group-item">
          <strong>Phone:</strong> {{ user.phone }}
        </li>
        <li class="list-group-item">
          <strong>Country:</strong>
          {% if user.country %}
          {{ user.country }}
          {%else %} 
          not added yet
          {% endif %}
        </li>
        <li class="list-group-item">
          <strong>BirthDate:</strong> 
          {% if user.birth_date %}
          {{user.birth_date}} 
          {% else %} 
          not added yet 
          {% endif %}
        </li>
        <li class="list-group-item">
          <strong>FaceBook Page:</strong> {% if user.facebook %} {{user.facebook }} {% else %} not added yet {% endif %}
        </li>
      </ul>

      <div class="mt-3">
        <a href="{% url 'user.edit' user.id %}" class="btn btn-primary mx-3">Edit</a>
        <form action="{% url 'user.delete' user.id %}" method="post" class="d-inline ">
          {% csrf_token %}
          <button type="button" onclick="confirmDelete(this)" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
  function confirmDelete(button) {
    Swal.fire({
      title: "Are you sure you want to delete your account?",
      text: "You won't be able to revert this!",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#d33",
      cancelButtonColor: "#3085d6",
      confirmButtonText: "Yes, delete it!",
    }).then((result) => {
      if (result.isConfirmed) {
        button.form.submit(); 
      }
    });
  }
</script>
{% endblock %}

crowdFunding/users/templates/users/user_donations.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link href="{% static 'users/css/styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container">
        <div class="text-center my-3">
            <h1 class="text-center text-success fw-bold fst-italic fs-1  text-capitalize mb-3">Donation Summary for {{ user.first_name }} {{ user.last_name }}</h1>

                <p class="d-inline-block me-5 fw-bold  fs-5">Total Donations: ${{ total_donation_user }}</p>
                <a class="d-inline-block btn btn-success ms-5" href="{% url 'user.projects' user.id %}">Go to your projects</a>

        </div>
        <div class="accordion" id="donations">
            {% if project_donations %}
                {% for donation in project_donations %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="heading{{ donation.project_id }}">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ donation.project_id }}" aria-expanded="true" aria-controls="collapse{{ donation.project_id }}">
                                Project title: {{ donation.project__title }}, Total Donation: ${{ donation.total_donation_project }}
                            </button>
                        </h2>
                        <div id="collapse{{ donation.project_id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ donation.project_id }}" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <ul>
                                    {% for user_donation in donation.user_donations %}
                                        <li>Donation Amount: ${{ user_donation.donation }}, Time: {{ user_donation.created_at }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p class="text-center text-danger fw-bold fs-3 text-capitalize mb-3">No donations have been made yet!</p>
            {% endif %}
        </div>
    </div>
    
{% endblock %}

crowdFunding/users/templates/users/user_edit.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<style>
  input
  {
      width:fit-content: !important;
  }
  body
  {
      background-color: lightgray;
  }
  input[type="text"], input[type="email"], input[type="url"], input[type="password"], input[type="file"]
  {
      margin-bottom: 8px; 
  }
</style>

</style>
  <h2 class="text-center mt-1">Edit User Data</h2>
  <form method="post" enctype="multipart/form-data" class="row w-50 mx-auto mt-1">
    {% csrf_token %} 
    {{ form }}
    <button type="submit" class="btn btn-success ">Edit</button>
  </form>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="{% static 'users/js/formStyles.js' %}"></script>
{% endblock %}

crowdFunding/users/templates/users/user_projects.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="container">
        <div class="row">
                <h1 class="text-center text-success fw-bold fst-italic fs-1 my-3 text-capitalize">Projects by User {{ user.first_name }} {{ user.last_name }}</h1>
                {% if projects %}
                        {% for project in projects %}
                        <div class="col-md-4 mb-4">
                                <div class="card">
                                {% if project.images.all %}
                                <img src="{{ project.images.first.image.url }}" class="card-img-top" alt="{{ project.title }}">
                        {% else %}
                                <!-- Placeholder image if project has no images -->
                                <img src="/media/project/images/default.jpg" class="card-img-top" alt="Placeholder">
                        {% endif %}
                                <div class="card-body">
                                        <h5 class="card-title">Title: {{ project.title }}</h5>
                                        <p class="card-text">Details: {{ project.details }}</p>
                                        <p class="card-text">Start Date: {{ project.start_date }}</p>
                                        <p class="card-text">Total Target: {{ project.total_target }}</p>
                                        {% comment %} <a href="{{ project.delete_url }}" class="btn btn-danger">Delete</a> {% endcomment %}
                                        <a href="{{ project.show_url }}" class="btn btn-info">Show</a>
                                        {% comment %} <a href="{{ project.edit_url }}" class="btn btn-primary">Edit</a> {% endcomment %}
                                        <a href="{{project.donate_url}}" class="btn btn-success">Donate</a>
                                </div>
                                </div>
                        </div>
                        {% endfor %}
                {% else %}
                        <div class="col-12">
                                <p class="text-center text-danger fw-bold fs-3 text-capitalize mb-3">You haven't started any projects yet!</p>
                        </div>
                {% endif %}
        </div>
        </div>
{% endblock %}